### ISSUE TITLE
Timestamps: incorrect timezone and format

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/yalcha#11]
Timestamps always have to be returned in UTC-0, with a "Z" at the end. Currently, yalcha returns times in UTC+03:00 timezone, without a time zone indicator:

https://vheirh41ic.execute-api.us-west-2.amazonaws.com/development/api/0.6/node/21265449/history

timestamp="2017-11-29T13:16:22"

https://api.openstreetmap.org/api/0.6/node/21265449/history

timestamp="2017-11-29T10:16:22Z"

**Comment by paulmach** [comment]
yes, a 'Z' needs to added to this constant https://github.com/osmlab/yalcha/blob/7bea019320fb651e15fe71107ddb6c3eae92605f/osm/helpers.go#L10

and probably some `.UTC()` added to the timestamps after they are loaded from the db. But it might be easier to just run the server in UTC.

**Comment by mmd-osm** [comment]
> But it might be easier to just run the server in UTC.

We had some issues in the Rails port when the local timezone was different from utc-0, and to my knowledge they've been fixed. I'm not aware of any hard requirement to run servers in UTC for the rest of the osm infra.

**Comment by mmd-osm** [comment]
It seems your patch is deployed now, at least I can see the Zulu character in the timestamp now.

`timestamp="2017-11-29T13:16:22Z"`

However, the actual timezone value still appears to be in UTC+3.

**Comment by pnorman** [comment]
You probably want to set your timezone to UTC when connecting to postgres
